# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

#target 'objc-best-practices' do
pod 'AFNetworking','~> 2.0'
pod 'JSONModel'
#end

target 'objc-best-practicesTests' do
pod 'OCHamcrest'
pod 'OCMockito'
end

